
subject_list: null

defaults:
  - _self_
  - dataset: null
  - parcellation: null
  - denoise: simple+gsr

smoothing_fwhm: 5.0

save_to_root: True
output_dir: ./outputs
compression: gzip
compression_opts: 4
