# @package _global_

space: T1w
use_template_gm: False
resample_gm: False
gm_path: ./atlases/tpl-sub*T1w/tpl-sub*T1w_res-func_label-GM_desc-fromFS_dseg.nii.gz
gm_name: indivGMfromFS

build_func_mask: True

parcel_type: mask
use_template_parcel: False
mask_parcel: True
parcellation: ./atlases/tpl-sub*T1w/tpl-sub*T1w_res-func_atlas-fLocVisionKanwisher_label-sceneMPA_mask.nii.gz

parcel_name: fLocVisionKanwisher
desc: sceneMPA
