# @package _global_

space: T1w
use_template_gm: False
resample_gm: False
gm_path: ./atlases/tpl-sub*T1w/tpl-sub*T1w_res-func_label-boldGMintersect_desc-fromFS_dseg.nii.gz
gm_name: indivBoldGMfromFS

build_func_mask: False

parcel_type: mask
use_template_parcel: False
mask_parcel: True
parcellation: ./atlases/tpl-sub*T1w/tpl-sub*T1w_res-func_label-boldGMintersect_desc-fromFS_dseg.nii.gz

parcel_name: Freesurfer
desc: BoldGM_res-func
