# @package _global_

space: MNI152NLin2009cAsym
use_template_gm: False
resample_gm: False
gm_path: ./atlases/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_sub-*_res-func_label-boldGMintersect_desc-fromFS_dseg.nii.gz
gm_name: indivBoldGMfromFS

build_func_mask: False

parcel_type: mask
use_template_parcel: False
mask_parcel: True
parcellation: ./atlases/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_sub-*_res-func_label-boldGMintersect_desc-fromFS_dseg.nii.gz

parcel_name: Freesurfer
desc: BoldGM_res-func
