# @package _global_

space: MNI152NLin2009cAsym
use_template_gm: False
resample_gm: False
gm_path: ./atlases/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_sub-0*_res-func_label-boldGMintersect_desc-fromFS_dseg.nii.gz
gm_name: indivBoldGMfromFS

build_func_mask: False 

parcel_type: dseg
use_template_parcel: True
mask_parcel: True
parcellation: ./atlases/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_atlas-Schaefer2018TianS3NettekovenAsym_desc-1000Parcels7Networks50Subcort128Cereb_dseg.nii.gz

parcel_name: Schaefer2018TianS3NettekovenAsym
desc: 1000Parcels7Networks50Subcort128Cereb